### ISSUE TITLE
How is the ground-truth output for SFT created?

### ISSUE THREAD

**Issue by WtaoZhao** [dongguanting/FollowRAG#1]
Hello, thanks for your excellent work in instruction-following in RAG scenarios. However, I was wondering how is the ground-truth output for SFT created? You mentioned that the original ground-truth might no longer be valid after adding diverse constraints.

**Comment by dongguanting** [comment]
In the SFT dataset, our grounding truth is synthesized using strong supervised model like GPT4 and dual verification by our generated code execution feedback and LLMs judgment.
